name: semantic_kitti_eval_to_vocab
canonical_to_vocab:
  car: car
  bicycle: bicycle
  motorcycle: motorcycle
  truck: truck
  bus: other vehicle
  other vehicle: other vehicle
  person: person
  pedestrian: person
  bicyclist: bicyclist
  motorcyclist: motorcyclist
  road: road
  parking: parking
  sidewalk: sidewalk
  other ground: other ground
  building: building
  fence: fence
  vegetation: vegetation
  trunk: trunk
  tree trunk: trunk
  terrain: terrain
  pole: pole
  traffic sign: traffic sign
