name: vkitti_train_to_vocab
canonical_to_vocab:
  terrain: terrain
  tree: tree
  vegetation: vegetation
  building: building
  road: road
  guardrail: guardrail
  traffic sign: traffic sign
  traffic light: traffic light
  pole: pole
  truck: truck
  car: car
  van: van
