task: nuscenes_day_to_night
source_dataset: nuscenes
target_dataset: nuscenes
datasets:
  nuscenes: configs/mappings/datasets/nuscenes_raw.yaml
vocab_maps:
  train: configs/mappings/vocab_maps/nuscenes_train_to_vocab.yaml
  eval: configs/mappings/vocab_maps/nuscenes_eval_to_vocab.yaml
  semantic_probe: configs/mappings/vocab_maps/nuscenes_eval_to_vocab.yaml
dataset_vocab_map:
  nuscenes:
    train: train
    eval: eval
    semantic_probe: semantic_probe
