prompt_templates:
  - "a photo of a {}."
  - "a point cloud of a {}."
  - "a driving scene with {}."
classes:
  - name: car
    aliases: ["vehicle car", "automobile"]
    seen: false
  - name: bus
    aliases: ["city bus"]
    seen: false
  - name: truck
    aliases: ["large vehicle", "lorry"]
    seen: false
  - name: pedestrian
    aliases: ["person walking"]
    seen: false
  - name: traffic cone
    aliases: ["road cone"]
    seen: false
  - name: driveable surface
    aliases: ["drivable road", "road surface"]
    seen: false
  - name: sidewalk
    aliases: ["walkway", "pedestrian sidewalk"]
    seen: false
  - name: vegetation
    aliases: ["plant", "tree", "green vegetation"]
    seen: false
  - name: manmade structure
    aliases: ["building", "manmade"]
    seen: false
  - name: barrier
    aliases: ["road barrier"]
    seen: false
